apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-tracker
  labels:
    app: schedule-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schedule-tracker
  template:
    metadata:
      labels:
        app: schedule-tracker
    spec:
      containers:
      - name: schedule-tracker
        image: schedule-tracker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: sqlite-data
          mountPath: /app/instance
      volumes:
      - name: sqlite-data
        persistentVolumeClaim:
          claimName: sqlite-pvc 