apiVersion: v1
kind: Service
metadata:
  name: schedule-tracker-service
spec:
  type: NodePort
  selector:
    app: schedule-tracker
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
